# Move the directory to the second line
format = '$all$directory$character'

[aws]
disabled = false
format = ' [$symbol ($profile )(\($region\) )]($style)'
symbol = 'ó°¸ '

[azure]
disabled = false
format = " [$symbol($subscription)]($style) "
symbol = "î¯˜ "
style = "blue bold"

[buf]
disabled = false
symbol = "ï’ "

[deno]
disabled = true
format = " [:sauropod: $version](green bold) "

[directory]
truncation_length = 2

[direnv]
disabled = false

[docker_context]
disabled = true
symbol = "ïŒˆ "

[git_branch]
symbol = "ï˜ "

[golang]
format = " [$symbol$version](cyan bold)"
symbol = "î˜§ "

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "

[kubernetes]
format = ' [ó±ƒ¾ $context](dimmed green) '
disabled = false
contexts = [
  { context_pattern = "dev.local.cluster.k8s", style = "green", symbol = "ğŸ’” " },
]

[nodejs]
disabled = false
symbol = "îœ˜ "
detect_extensions = []

[red]
disabled = true

[rust]
disabled = false
format = "[$symbol$version](red bold)"
symbol = "î¨ "


