format = '$all$directory$character'

[aws]
disabled = false
format = ' [$symbol ($profile )(\($region\) )]($style)'
symbol = '󰸏 '

[azure]
disabled = true
format = " [$symbol($subscription)]($style) "
symbol = " "
style = "blue bold"

[gcloud]
disabled = true

[buf]
disabled = false
symbol = " "

[deno]
disabled = true
format = " [:sauropod: $version](green bold) "

[directory]
truncation_length = 2

[direnv]
disabled = false
style = "green"
format = "[$symbol$loaded/$allowed]($style)"
 
[docker_context]
disabled = true
symbol = " "

[git_branch]
symbol = " "

[golang]
format = "[$symbol$version](cyan bold) "
symbol = " "

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "

[kubernetes]
format = ' [󱃾 $context](dimmed blue) '
disabled = false

[nodejs]
disabled = true
symbol = " "
detect_extensions = []

[red]
disabled = true

[rust]
disabled = false
format = "[$symbol$version](red bold) "
symbol = " "

[fossil_branch]
disabled = true
